name: CI/CD Pipeline

on: 
  push:
    branches:
      - main  # Runs the workflow when code is pushed to the 'main' branch

jobs:
  verify-and-package:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 14 for Maven
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 14

      # Step 3: Run Maven tests and build the WAR file
      - name: Run all tests and build
        run: mvn -B verify --file pom.xml

      # Step 4: Login to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Automatically uses your GitHub username
          password: ${{ secrets.PAT }}   # Replace PAT with your Personal Access Token secret

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                     # Directory containing your Dockerfile
          push: true                     # Pushes the image to GHCR
          tags: ghcr.io/${{ github.actor }}/my-image:latest
